### ISSUE TITLE
Add proper currency support for PayPal donations

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/harbor-wp-theme#36]
**Codes:** https://developer.paypal.com/docs/classic/api/currency_codes/

**Array structure:**

``` php
$currency = array(
    'AAA' => array(
        'name' => 'Name (ex. Canadian Dollar)',
        'symbol' => '$',
    )
);
```

**Comment by barokoko** [comment]
Sorry for no investigation from my side, but this issue sounds like a general problem with currencies and I hesitate to try it with Euro for donations on a children-help website.

**Comment by cferdinandi** [comment]
Deprecating this project and will no longer be making updates. Closing this issue accordingly.
