### ISSUE TITLE
Pulling Forwarded Site in at Header and Footer when working from mapped hosts file.

### ISSUE THREAD

**Issue by MikeiLL** [cferdinandi/harbor-wp-theme#60]
Not sure exactly why this is happening yet, but am working on a site who's domain name still points to the previous host. So have updated the hosts file on the local development machine so that www.theshelterinquestion.com is mapped to the development server's IP address.

The URL www.theshelterinquestion.com is forwarded to a petfinder "site" (actually a single page), and the contents of this page are being pulled embedded into both the header and footer of the Harbor theme. Never seen this before. Not happening with any of the default WP themes.

I hope the description is clear. The embedding is occurring at:

```
        <script type='text/javascript' src='http://www.theshelterinquestion.com/wp/wp-includes/js/admin-bar.min.js?ver=4.4.2'></script>
```

<script type='text/javascript' src='http://www.theshelterinquestion.com/wp/wp-includes/js/wp-embed.min.js?ver=4.4.2'></script>

```
        <script> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> ALL HTML FROM PAGE HERE...

    if ( 'querySelector' in document && 'addEventListener' in window ) {
                loadJS('http://www.theshelterinquestion.com/wp/wp-content/themes/harbor-wp-theme/dist/js/main.min.2.16.0.js');
                // loadJS('http://www.theshelterinquestion.com/wp/wp-content/themes/harbor-wp-theme/dist/js/main.js');
```

I think the solution may be in removing the domain name from the 'loadJS' call and just calling from the relative directory.

I imagine I can work around it if I'm able to update the hosts file on the shared server, or by actually "going live" with the site, but it would be nice to determine the cause of this behavior.

**Comment by cferdinandi** [comment]
I'm afraid I'm going to have to close this one out as wildly out of scope for this project. There are just too many variables and unknowns that I have no visibility to and can't speak to. Sorry!

**Comment by MikeiLL** [comment]
The two functions that are causing the issue are `keel_load_inline_footer` and `keel_load_inline_header`. I tried, briefly and unsuccessfully, to use a full path rather than a URI by replacing `get_template_directory_uri()` with `get_template_directory()`. It seems like the theme should work even with DNS not being set-up, but for now I'm just going to comment out `add_action('wp_head', 'keel_load_inline_header', 30);` and also the `keel_load_inline_footer` reference until DNS is changed.
